namespace PoE2LevelingCompanion.Models;

public static class ZoneData
{
    public static readonly (string Act, string[] Zones)[] CampaignZones =
    [
        ("Act 1", [
            "The Riverbank",
            "Clearfell Encampment",
            "Clearfell",
            "The Mud Burrow",
            "The Grelwood",
            "The Red Vale",
            "The Grim Tangle",
            "Cemetery of the Eternals",
            "Tomb of the Consort",
            "Mausoleum of the Praetor",
            "Freythorn",
            "The Hunting Grounds",
            "Ogham Farmlands",
            "Ogham Village",
            "The Manor Ramparts",
            "Ogham Manor",
        ]),
        ("Act 2", [
            "Vastiri Outskirts",
            "The Ardura Caravan",
            "Mawdun Quarry",
            "Mawdun Mine",
            "The Halani Gates",
            "Traitor's Passage",
            "Mastodon Badlands",
            "The Bone Pits",
            "Keth",
            "The Lost City",
            "Buried Shrines",
            "Valley of the Titans",
            "The Titan Grotto",
            "Deshar",
            "Path of Mourning",
            "The Spires of Deshar",
            "The Dreadnought",
        ]),
        ("Act 3", [
            "Sandswept Marsh",
            "Ziggurat Encampment",
            "Jungle Ruins",
            "The Venom Crypts",
            "Infested Barrens",
            "The Matlan Waterways",
            "Chimeral Wetlands",
            "Jiquani's Machinarium",
            "Jiquani's Sanctum",
            "The Drowned City",
            "The Molten Vault",
            "Apex of Filth",
            "Temple of Kopec",
            "The Azak Bog",
            "Utzaal",
            "Aggorat",
            "The Black Chambers",
            "The Temple of Chaos",
        ]),
        ("Act 4", [
            "Kingsmarch",
            "Isle of Kin",
            "Volcanic Warrens",
            "Kedge Bay",
            "Journey's End",
            "Abandoned Prison",
            "Solitary Confinement",
            "Whakapanu Island",
            "Singing Caverns",
            "Shrike Island",
            "Eye of Hinekora",
            "Halls of the Dead",
            "Arastas",
            "The Excavation",
            "Ngakanu",
            "Heart of the Tribe",
            "Plunder's Point",
            "Trial of the Ancestors",
        ]),
        ("Interlude 1 — Curse of Holten", [
            "The Refuge",
            "Scorched Farmlands",
            "Stones of Serle",
            "The Blackwood",
            "Holten",
            "Wolvenhold",
            "Holten Estate",
        ]),
        ("Interlude 2 — The Stolen Barya", [
            "The Khari Bazaar",
            "The Khari Crossing",
            "Pools of Khatal",
            "Sel Khari Sanctuary",
            "The Galai Gates",
            "Qimah",
            "Qimah Reservoir",
        ]),
        ("Interlude 3 — Doryani's Contingency", [
            "The Glade",
            "Ashen Forest",
            "Kriar Village",
            "Glacial Tarn",
            "Howling Caves",
            "Kriar Peaks",
            "Etched Ravine",
            "The Cuachic Vault",
        ]),
    ];

    public static readonly string[] Classes =
    [
        "Warrior",
        "Mercenary",
        "Monk",
        "Witch",
        "Huntress",
        "Druid",
        "Blood Mage",
        "Deadeye",
        "Gemling Legionnaire",
        "Infernalist",
        "Martial Artist",
        "Oracle",
        "Ritualist",
    ];
}
